pl_trainer:
  max_epochs: 100
  devices:
  - 2
  accelerator: gpu

# should match arguments in the BrainPatchesDataModule class
dataset:
  patches:
    window_size: 64
    stride: 32
    img_threshold: 0.5
    normalization: z_score
    denoiser: False # add functionality to add new channel of rough segmentation
    augmentation: True

  train_num_workers: 8
  train_batch_size: 64
  val_num_workers: 8
  val_batch_size: 64

# should match arguments in the module class
model:
  n_classes: 4
  in_channels: 1
  feature_scale: 4

  loss: cross_entropy # dice, cross_entropy, focal, tversky
  lr: 0.001
  model: "UNet_3Plus" # UNet_3Plus, UNet_2Plus or UNet

exp_name: unet3p_augm_bce_64_05